package basic.exception;

import java.util.Scanner;

public class ExceptionTest03 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.print("id : "); String user_id = sc.nextLine();
		System.out.print("pw : "); String user_pw = sc.nextLine();
		
		MemberVO userInfo = new MemberVO();
		userInfo.setUser_id(user_id);
		userInfo.setUser_pw(user_pw);
		
		try {
			userInfo = login(userInfo);
			System.out.println(userInfo.getUser_name() + "님이 로그인 하였습니다.");
		} catch (RuntimeException e) {
			System.out.println(e.getMessage());
		}
			
		
	}

	private static MemberVO login(MemberVO userInfo) throws RuntimeException {
		if (userInfo.getUser_id().equals("multi") &&
			userInfo.getUser_pw().equals("fa585d89c851dd338a70dcf535aa2a92fee7836dd6aff1226583e88e0996293f16bc009c652826e0fc5c706695a03cddce372f139eff4d13959da6f1f5d3eabe")){
			userInfo.setUser_name("제이비");
			return userInfo;
		} else {
			throw new RuntimeException("아이디 혹은 비밀번호가 틀릴걸요?");
		}
	}
}
